# syntax=docker/dockerfile:1

FROM python:3.9-alpine

WORKDIR /app
ENV TZ=Europe/Paris
COPY requirements-telegram.txt requirements-telegram.txt
RUN pip3 install -r requirements-telegram.txt

COPY ./send_telegram_message.py ./send_telegram_message.py

CMD [ "python3", "-u", "send_telegram_message.py"]