name: 'Publish new scraper version'

on:
  push:
    branches:
      - main

jobs:
  publish-web-client:
    name: Build and publish new scraper docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mathieugery/scrapastats/scrapastats:latest
  publish-telegram-notifications:
    name: Build and publish new telegram notifications docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.telegram
          push: true
          tags: ghcr.io/mathieugery/scrapastats/scrapastats-telegram-notifications:latest